Add additional repositories
NorddeutscherRundfunk/terraform-workload-identity-federation pull request #1
Opened 2022-08-16 12:43 UTC by muffl0n

2022-08-16 12:51 UTC, Sevenlive requested changes

2022-08-16 12:51 UTC, Sevenlive commented on output.tf
> +output "workload_identity_pool_name" {
Brauchen wir die Outputs dann überhaupt noch?

2022-08-17 06:55 UTC, muffl0n commented on output.tf
> +output "workload_identity_pool_name" {
Hm, vermutlich nicht. Ich werf's raus. Danke! ❤️

2022-08-17 07:07 UTC, muffl0n commented
`formatlist()` ftw!
```
  # module.wif.google_service_account_iam_binding.workload will be created
  + resource "google_service_account_iam_binding" "workload" {
      + etag               = (known after apply)
      + id                 = (known after apply)
      + members            = [
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-Hospitalisierungsmaschinenraum",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-Infra",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-docker-images",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-flugverspaetungen",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-greenwashing_etfs",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-inflation",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-inzidenz-prognose-analyse",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-pegelstaende",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-sensoren",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-sitemetriken",
          + "principalSet://iam.googleapis.com/projects/935922253324/locations/global/workloadIdentityPools/github/attribute.repository/NorddeutscherRundfunk/NDRData-waldbraende",
        ]
      + role               = "roles/iam.workloadIdentityUser"
      + service_account_id = "projects/ndrdata-infra/serviceAccounts/tf-github@ndrdata-infra.iam.gserviceaccount.com"
    }
```

2022-08-17 14:00 UTC, Sevenlive approved these changes

2022-08-17 14:10 UTC, merged

2022-08-17 14:11 UTC, muffl0n commented
Tag v0.0.2 ist auch gesetzt.